# Generated by Django 6.0.5 on 2026-06-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='proactive',
            field=models.BooleanField(default=False),
        ),
    ]
